-- MySQL Script generated by MySQL Workbench
-- 10/21/16 16:54:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estados` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `observacion` TEXT NULL,
  `cantidadcuotaadeuda` INT NULL,
  `estadoposterior` VARCHAR(45) NULL,
  `cuotainteres` DECIMAL(11,2) NULL,
  `tipo` VARCHAR(45) NULL DEFAULT 'Activo',
  `imprimecupon` VARCHAR(45) NULL DEFAULT 'Si',
  `reingreso` VARCHAR(45) NULL DEFAULT 'Si',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `observacion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `descripcionbreve` VARCHAR(8) NULL,
  `importeinscripcion` DECIMAL(11,2) NULL,
  `importecuota` DECIMAL(11,2) NULL,
  `incluyemora` VARCHAR(45) NULL DEFAULT 'Si',
  `edadesde` VARCHAR(45) NULL DEFAULT '18',
  `edadhasta` VARCHAR(45) NULL DEFAULT '199',
  `derechovoto` VARCHAR(45) NULL DEFAULT 'Si',
  `tipos_id` INT UNSIGNED NOT NULL,
  `cantidadfamiliares` INT NULL,
  `cantidadavalantes` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categorias_tipos1_idx` (`tipos_id` ASC),
  CONSTRAINT `fk_categorias_tipos1`
    FOREIGN KEY (`tipos_id`)
    REFERENCES `mydb`.`tipos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`socios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`socios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nsocio` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `lugarnacimiento` VARCHAR(45) NULL,
  `fechanacimiento` DATE NULL,
  `dni` DECIMAL(10,0) NULL,
  `estadocivil` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `fechaalta` DATETIME NULL,
  `fechabaja` DATETIME NULL,
  `foto` VARCHAR(45) NULL,
  `acta` VARCHAR(45) NULL,
  `libro` VARCHAR(45) NULL,
  `formadepago` VARCHAR(45) NULL DEFAULT 'Club',
  `estados_id` INT UNSIGNED NOT NULL,
  `categorias_id` INT UNSIGNED NOT NULL,
  `situacionmilitar` VARCHAR(45) NULL DEFAULT 'Activo',
  `grado` VARCHAR(45) NULL,
  `fuerza` VARCHAR(45) NULL,
  `escalafon` VARCHAR(45) NULL,
  `promovidopor` VARCHAR(45) NULL,
  `serviciosen` VARCHAR(45) NULL,
  `serviciodesde` DATE NULL,
  `serviciohasta` DATE NULL,
  `utilizaembarcadero` VARCHAR(45) NULL DEFAULT 'No',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `codigo_UNIQUE` (`nsocio` ASC),
  INDEX `fk_socios_estados_idx` (`estados_id` ASC),
  INDEX `fk_socios_categorias1_idx` (`categorias_id` ASC),
  CONSTRAINT `fk_socios_estados`
    FOREIGN KEY (`estados_id`)
    REFERENCES `mydb`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_socios_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `mydb`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`familiares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`familiares` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  `fechanacimiento` DATETIME NULL,
  `parentesco` VARCHAR(45) NULL,
  `socios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_familiares_socios1_idx` (`socios_id` ASC),
  CONSTRAINT `fk_familiares_socios1`
    FOREIGN KEY (`socios_id`)
    REFERENCES `mydb`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zonas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `observacion` VARCHAR(45) NULL,
  `barrio` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cobradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cobradores` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  `domicilio` VARCHAR(45) NULL,
  `barrio` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `zonas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cobradores_zonas1_idx` (`zonas_id` ASC),
  CONSTRAINT `fk_cobradores_zonas1`
    FOREIGN KEY (`zonas_id`)
    REFERENCES `mydb`.`zonas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actividad` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `importe` DECIMAL(11,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `importe` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actividad_has_socios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actividad_has_socios` (
  `actividad_id` INT NOT NULL,
  `socios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`actividad_id`, `socios_id`),
  INDEX `fk_actividad_has_socios_socios1_idx` (`socios_id` ASC),
  INDEX `fk_actividad_has_socios_actividad1_idx` (`actividad_id` ASC),
  CONSTRAINT `fk_actividad_has_socios_actividad1`
    FOREIGN KEY (`actividad_id`)
    REFERENCES `mydb`.`actividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_has_socios_socios1`
    FOREIGN KEY (`socios_id`)
    REFERENCES `mydb`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicios_has_socios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicios_has_socios` (
  `servicios_id` INT NOT NULL,
  `socios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`servicios_id`, `socios_id`),
  INDEX `fk_servicios_has_socios_socios1_idx` (`socios_id` ASC),
  INDEX `fk_servicios_has_socios_servicios1_idx` (`servicios_id` ASC),
  CONSTRAINT `fk_servicios_has_socios_servicios1`
    FOREIGN KEY (`servicios_id`)
    REFERENCES `mydb`.`servicios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicios_has_socios_socios1`
    FOREIGN KEY (`socios_id`)
    REFERENCES `mydb`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contactos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL DEFAULT 'Personal',
  `socios_id` INT UNSIGNED NOT NULL,
  `domicilio` VARCHAR(120) NULL,
  `barrio` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  `cp` INT NULL,
  `telefono` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `cobra` VARCHAR(45) NULL DEFAULT 'No',
  `zonas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contactos_socios1_idx` (`socios_id` ASC),
  INDEX `fk_contactos_zonas1_idx` (`zonas_id` ASC),
  CONSTRAINT `fk_contactos_socios1`
    FOREIGN KEY (`socios_id`)
    REFERENCES `mydb`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contactos_zonas1`
    FOREIGN KEY (`zonas_id`)
    REFERENCES `mydb`.`zonas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias_has_actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias_has_actividad` (
  `categorias_id` INT UNSIGNED NOT NULL,
  `actividad_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`categorias_id`, `actividad_id`),
  INDEX `fk_categorias_has_actividad_actividad1_idx` (`actividad_id` ASC),
  INDEX `fk_categorias_has_actividad_categorias1_idx` (`categorias_id` ASC),
  CONSTRAINT `fk_categorias_has_actividad_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `mydb`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categorias_has_actividad_actividad1`
    FOREIGN KEY (`actividad_id`)
    REFERENCES `mydb`.`actividad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cobradores_has_socios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cobradores_has_socios` (
  `cobradores_id` INT UNSIGNED NOT NULL,
  `socios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`cobradores_id`, `socios_id`),
  INDEX `fk_cobradores_has_socios_socios1_idx` (`socios_id` ASC),
  INDEX `fk_cobradores_has_socios_cobradores1_idx` (`cobradores_id` ASC),
  CONSTRAINT `fk_cobradores_has_socios_cobradores1`
    FOREIGN KEY (`cobradores_id`)
    REFERENCES `mydb`.`cobradores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cobradores_has_socios_socios1`
    FOREIGN KEY (`socios_id`)
    REFERENCES `mydb`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`socios_has_socios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`socios_has_socios` (
  `socios_id` INT UNSIGNED NOT NULL,
  `socios_id1` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`socios_id`, `socios_id1`),
  INDEX `fk_socios_has_socios_socios2_idx` (`socios_id1` ASC),
  INDEX `fk_socios_has_socios_socios1_idx` (`socios_id` ASC),
  CONSTRAINT `fk_socios_has_socios_socios1`
    FOREIGN KEY (`socios_id`)
    REFERENCES `mydb`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_socios_has_socios_socios2`
    FOREIGN KEY (`socios_id1`)
    REFERENCES `mydb`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`militares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`militares` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  `grado` VARCHAR(45) NULL,
  `fuerza` VARCHAR(45) NULL,
  `escalafon` VARCHAR(45) NULL,
  `promovidopor` VARCHAR(45) NULL,
  `serviciosdesde` DATE NULL,
  `servicioshasta` DATE NULL,
  `serviciosen` VARCHAR(45) NULL,
  `socios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_militares_socios1_idx` (`socios_id` ASC),
  CONSTRAINT `fk_militares_socios1`
    FOREIGN KEY (`socios_id`)
    REFERENCES `mydb`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias_has_servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorias_has_servicios` (
  `categorias_id` INT UNSIGNED NOT NULL,
  `servicios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`categorias_id`, `servicios_id`),
  INDEX `fk_categorias_has_servicios_servicios1_idx` (`servicios_id` ASC),
  INDEX `fk_categorias_has_servicios_categorias1_idx` (`categorias_id` ASC),
  CONSTRAINT `fk_categorias_has_servicios_categorias1`
    FOREIGN KEY (`categorias_id`)
    REFERENCES `mydb`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categorias_has_servicios_servicios1`
    FOREIGN KEY (`servicios_id`)
    REFERENCES `mydb`.`servicios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
