GET https://jsonplaceholder.typicode.com/posts

###

POST https://jsonplaceholder.typicode.com/posts
Content-Type: : application/json

{
    "title": "POST DE PRUEBA",
    "body": "DESCRIPCION POST DE PRUEBA"
}